<script type="text/javascript">
    jQuery(document).ready(function () {
        var SiteOptionsForm = {
            action: "changeSiteOptions",
            label: "Site Options",
            fields: [
                {
                    label: "Title",
                    id: "title",
                    type: "text",
                    value: "2"
                },
                {
                    label: "Meta keywords",
                    id: "meta_keywords",
                    type: "textarea",
                    value: "lorem"
                },
                {
                    label: "Meta description",
                    id: "meta_description",
                    type: "text",
                    value: "lorem"
                }
            ]
        };

        var MyForms = [
            {
                elements: [".liveedit"],
                label: "HTML LiveEdit Form",
                fields: [
                    {
                        label: "Content",
                        id: "html-edit",
                        type: "html",
                        value: function (element) {
                            return jQuery(element).text();
                        }
                    }
                ]
            }
        ];

        LiveEditorToolbar.init({
            SiteOptions: SiteOptionsForm,
            FormObjects: MyForms,
            editPNG: "<?php echo $this->getSkinUrl('images/divante_liveeditor/edit.png'); ?>",
            viewPNG: "<?php echo $this->getSkinUrl('images/divante_liveeditor/view.png'); ?>"
        });
    });
</script>

<div class="overlay" style="display:none"></div>
<div id="le_form_markup" style="display:none">
    <div id="le_form_title"></div>
    <div id="le_form_body">
        <form id="le_form_form">
            <input type="hidden" name="referer_action" value="<?php echo Divante_LiveEditor_LiveEditor::getInstance()->getActionIdentifier(); ?>" />
            <input type="hidden" name="id" value="<?php echo Divante_LiveEditor_LiveEditor::getInstance()->getActionParam('id'); ?>" />
            <fieldset>

            </fieldset>
        </form>
    </div>
    <div id="le_form_footer">
        <div id="le_form_close" class="button">Cancel</div>
        <div class="button">Save</div>
    </div>

</div>

<div id="le_toolbar">
    <div class="le_toolbar_left">
        <img src="<?php echo $this->getSkinUrl('images/divante_liveeditor/logo.gif'); ?>"/>
        <div class="button le_modeselector"><img style="width:24px;height:24px" src="<?php echo $this->getSkinUrl('images/divante_liveeditor/edit.png'); ?>"/>
            <p class="le_modeselector_text">Edit</p>
        </div>
    </div>
    <div class="le_toolbar_center">
        <div class="activeElement">Active Element</div>
        <div class="currentMode">View mode</div>
    </div>
    <div class="le_toolbar_right">
        <div class="loggedUser">loggedUser</div>
        <div class="le_toolbar_buttons">
            <a class="le_toolbar_singlebutton le_logout_button" href="#">Logout</a>
            <a class="le_toolbar_singlebutton le_admin_page_button" href="#">Admin Page</a>
            <a class="le_toolbar_singlebutton le_site_options_button">Site Options</a>

        </div>
    </div>



</div>
<div class="clear"></div>