<div id="le_form_markup" style="display:none">
    <div id="le_form_title"></div>
    <div id="le_form_body">
        <form id="le_form_form">
            <fieldset>

            </fieldset>
        </form>
    </div>
</div>

<div class="header">

    <div class="header-top">
        <div id="le_toolbar">
            <div class="le_toolbar_left">
                <img src="<?php echo $this->getSkinUrl('images/divante_liveeditor/logo.gif'); ?>"/>
            </div>
            <div class="le_toolbar_center">
                <div class="activeElement">Active Element</div>
            </div>
            <div class="le_toolbar_right">
                <div class="loggedUser">loggedUser</div>
                <div class="le_toolbar_buttons">
                    <a class="le_toolbar_singlebutton" href="#">Logout</a>
                    <a class="le_toolbar_singlebutton" href="#">Admin Page</a>
                    <div id="le_site_options" class="le_toolbar_singlebutton">Site Options</div>

                </div>
            </div>
        </div>

    </div>
    <div class="clear"></div>
</div>